# Generated by Django 5.1.5 on 2025-09-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
            },
        ),
    ]
