# Generated by Django 5.1.5 on 2025-09-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatresource",
            name="file_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OpenAI fayl ID.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="vector_stores_id",
            field=models.CharField(
                blank=True, help_text="Vector stores id.", max_length=128, null=True
            ),
        ),
    ]
