# Generated by Django 5.1.5 on 2025-09-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatresource_file_id_chatroom_vector_stores_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="vector_stores_id",
            new_name="vector_store_id",
        ),
    ]
