# Generated by Django 5.1.5 on 2025-09-25 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_specialization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="AI uchun foydali kontekst ma'lumotlari.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Foydalanuvchining muhim konteksti (AI uchun).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
