# Generated by Django 5.1.5 on 2025-09-25 11:45

import apps.shared.encoders.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_usercontext"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercontext",
            options={
                "verbose_name": "User Context",
                "verbose_name_plural": "User Contexts",
            },
        ),
        migrations.AlterField(
            model_name="usercontext",
            name="data",
            field=models.JSONField(
                default=dict,
                encoder=apps.shared.encoders.encoder.PrettyJSONEncoder,
                help_text="AI uchun foydali kontekst ma'lumotlari.",
            ),
        ),
        migrations.AlterModelTable(
            name="usercontext",
            table="user_contexts",
        ),
    ]
